include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - lib/l10n/generated/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    directives_ordering: true
    unawaited_futures: true
    avoid_redundant_argument_values: true
    prefer_const_constructors: true
    sort_child_properties_last: true
    use_super_parameters: true
