"""agents et cash orders

Revision ID: 2aede72617e9
Revises: 3b536d14e932
Create Date: 2026-09-08 21:43:57.047284
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2aede72617e9'
down_revision: str | None = '3b536d14e932'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('float_available_minor', sa.BigInteger(), nullable=False),
    sa.Column('float_cap_minor', sa.BigInteger(), nullable=False),
    sa.Column('commission_bps', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('float_available_minor <= float_cap_minor', name=op.f('ck_agents_float_within_cap')),
    sa.CheckConstraint('float_available_minor >= 0', name=op.f('ck_agents_float_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agents_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('user_id', name=op.f('uq_agents_user_id'))
    )
    op.create_table('cash_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ledger_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_cash_orders_client_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_orders'))
    )
    op.create_index('ix_cash_orders_client_id', 'cash_orders', ['client_id'], unique=False)
    op.create_index('ux_cash_orders_pending_code', 'cash_orders', ['code_hash'], unique=True, postgresql_where=sa.text("status = 'INITIATED' AND code_hash IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_cash_orders_pending_code', table_name='cash_orders', postgresql_where=sa.text("status = 'INITIATED' AND code_hash IS NOT NULL"))
    op.drop_index('ix_cash_orders_client_id', table_name='cash_orders')
    op.drop_table('cash_orders')
    op.drop_table('agents')
    # ### end Alembic commands ###
