"""demandes de paiement

Revision ID: 525c7bbcd54e
Revises: 85bd2771d0a5
Create Date: 2026-09-08 22:22:00.369251
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '525c7bbcd54e'
down_revision: str | None = '85bd2771d0a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('payer_id', sa.String(length=36), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resulting_transfer_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_payment_requests_amount_positive')),
    sa.CheckConstraint('requester_id <> payer_id', name=op.f('ck_payment_requests_not_self_request')),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], name=op.f('fk_payment_requests_payer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_payment_requests_requester_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_requests'))
    )
    op.create_index('ix_payment_requests_payer_id', 'payment_requests', ['payer_id'], unique=False)
    op.create_index('ix_payment_requests_requester_id', 'payment_requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_requests_requester_id', table_name='payment_requests')
    op.drop_index('ix_payment_requests_payer_id', table_name='payment_requests')
    op.drop_table('payment_requests')
    # ### end Alembic commands ###
