"""cas kyc et documents

Revision ID: 85bd2771d0a5
Revises: 2aede72617e9
Create Date: 2026-09-08 22:08:56.017989
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '85bd2771d0a5'
down_revision: str | None = '2aede72617e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_tier', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kyc_cases_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_cases'))
    )
    op.create_index('ix_kyc_cases_user_id', 'kyc_cases', ['user_id'], unique=False)
    op.create_index('ux_kyc_cases_one_pending_per_user', 'kyc_cases', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('kyc_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['kyc_cases.id'], name=op.f('fk_kyc_documents_case_id_kyc_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_documents')),
    sa.UniqueConstraint('case_id', 'kind', name=op.f('uq_kyc_documents_case_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyc_documents')
    op.drop_index('ux_kyc_cases_one_pending_per_user', table_name='kyc_cases', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_kyc_cases_user_id', table_name='kyc_cases')
    op.drop_table('kyc_cases')
    # ### end Alembic commands ###
