"""marchands qr et paiements

Revision ID: 99ff1e0011bf
Revises: 525c7bbcd54e
Create Date: 2026-09-08 22:35:34.379376
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '99ff1e0011bf'
down_revision: str | None = '525c7bbcd54e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee_bps', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fee_bps >= 0 AND fee_bps <= 1000', name=op.f('ck_merchants_fee_bps_bounds')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchants_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants')),
    sa.UniqueConstraint('user_id', name=op.f('uq_merchants_user_id'))
    )
    op.create_table('merchant_charges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_by', sa.String(length=36), nullable=True),
    sa.Column('ledger_transaction_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_merchant_charges_amount_positive')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_merchant_charges_merchant_id_merchants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_charges'))
    )
    op.create_index('ix_merchant_charges_merchant_id', 'merchant_charges', ['merchant_id'], unique=False)
    op.create_table('merchant_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payer_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('charge_id', sa.String(length=36), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('ledger_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_merchant_payments_merchant_id_merchants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], name=op.f('fk_merchant_payments_payer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_payments')),
    sa.UniqueConstraint('ledger_transaction_id', name=op.f('uq_merchant_payments_ledger_transaction_id'))
    )
    op.create_index('ix_merchant_payments_merchant_id', 'merchant_payments', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_merchant_payments_merchant_id', table_name='merchant_payments')
    op.drop_table('merchant_payments')
    op.drop_index('ix_merchant_charges_merchant_id', table_name='merchant_charges')
    op.drop_table('merchant_charges')
    op.drop_table('merchants')
    # ### end Alembic commands ###
