"""schéma initial

Revision ID: d9a7993720f0
Revises: 
Create Date: 2026-09-08 18:13:19.802583
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd9a7993720f0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    op.create_index('ix_idempotency_keys_expires_at', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('owner_ref', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_accounts'))
    )
    op.create_index('ux_ledger_accounts_identity', 'ledger_accounts', ['type', 'currency', 'owner_ref'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reverses_transaction_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['reverses_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_ledger_transactions_reverses_transaction_id_ledger_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_transactions'))
    )
    op.create_index('ix_ledger_transactions_reference', 'ledger_transactions', ['reference'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index('ix_outbox_unpublished', 'outbox', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('kyc_tier', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('kyc_tier between 0 and 2', name=op.f('ck_users_kyc_tier_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('ledger_postings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=True),
    sa.Column('analytic', sa.String(length=64), nullable=True),
    sa.CheckConstraint("direction in ('DEBIT','CREDIT')", name=op.f('ck_ledger_postings_direction_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_ledger_postings_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], name=op.f('fk_ledger_postings_account_id_ledger_accounts')),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], name=op.f('fk_ledger_postings_transaction_id_ledger_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_postings'))
    )
    op.create_index('ix_ledger_postings_account_id', 'ledger_postings', ['account_id'], unique=False)
    op.create_index('ix_ledger_postings_wallet_id', 'ledger_postings', ['wallet_id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('msisdn', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_phone_numbers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_numbers')),
    sa.UniqueConstraint('msisdn', name=op.f('uq_phone_numbers_msisdn'))
    )
    op.create_index('ix_phone_numbers_user_id', 'phone_numbers', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('available_minor', sa.BigInteger(), nullable=False),
    sa.Column('reserved_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_minor >= 0', name=op.f('ck_wallets_available_non_negative')),
    sa.CheckConstraint('reserved_minor >= 0', name=op.f('ck_wallets_reserved_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('user_id', 'currency', name=op.f('uq_wallets_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_index('ix_phone_numbers_user_id', table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index('ix_ledger_postings_wallet_id', table_name='ledger_postings')
    op.drop_index('ix_ledger_postings_account_id', table_name='ledger_postings')
    op.drop_table('ledger_postings')
    op.drop_table('users')
    op.drop_index('ix_outbox_unpublished', table_name='outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox')
    op.drop_index('ix_ledger_transactions_reference', table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index('ux_ledger_accounts_identity', table_name='ledger_accounts', postgresql_nulls_not_distinct=True)
    op.drop_table('ledger_accounts')
    op.drop_index('ix_idempotency_keys_expires_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
